title: 'Joseph L. Harun - Portfolio'
default_lang: en
author:
  name: 'Joseph L. Harun'
  email: josephlharun@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Brief description of Joseph L. Harun and his portfolio.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
